##Input Hyperparameter Tuning

pada scenario ini, hasil hyperparameter tuning pada Scenario 5 di implementasi pada ANN

##Import Library

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
import pandas as pd
import numpy as np
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.layers import Dense, Dropout

In [ ]:
df = pd.read_csv('socialfeature_liwc_roberta.csv')
df.head()

id     label          akun  jml_follower  jml_following  mention  hashtag  \
0   1  Openness   ridhorisali           242            247     2899      178   
1   2  Openness   annisadells           201            140      409      162   
2   3  Openness        12290F            63            217     2549      146   
3   4  Openness       abiyoga            16             37       99       13   
4   5  Openness  adityarestya            44             85      197      248   

   website  retweet  media_url  ...   758   759   760   761   762   763   764  \
0       59      311         17  ...  0.10  0.00 -0.16  0.05 -0.05 -0.19  0.24   
1       92      308        125  ...  0.12  0.02 -0.14  0.03 -0.10 -0.19  0.30   
2      489      814        440  ...  0.12 -0.04 -0.17 -0.02 -0.14 -0.17  0.44   
3       23       63         19  ...  0.09  0.02 -0.15  0.04 -0.12 -0.12  0.34   
4      211       31          9  ...  0.17  0.04 -0.20  0.04 -0.04 -0.21  0.33   

    765   766   767  
0 -0.31 -0.01  0.05  
1 -0.28 -0.03  0.00  
2 -0.40  0.01  0.05  
3 -0.31 -0.01  0.03  
4 -0.24 -0.01 -0.01  

[5 rows x 991 columns]

In [ ]:
df.drop(['id','akun'], axis=1, inplace=True)

##Alokasi data X dan y

In [ ]:
X = df.iloc[:, 1:]

In [ ]:
y = df.iloc[: , :1]

In [ ]:
X

jml_follower  jml_following  mention  hashtag  website  retweet  \
0             242            247     2899      178       59      311   
1             201            140      409      162       92      308   
2              63            217     2549      146      489      814   
3              16             37       99       13       23       63   
4              44             85      197      248      211       31   
..            ...            ...      ...      ...      ...      ...   
315             6             27        8        0        0        1   
316             0              2        0        0        0        0   
317           190            284     4762      708      936      386   
318            31             76      196        9       27       33   
319             8             59      156      146        9      104   

     media_url  tanda_baca  huruf_kapital  jml_tweet  ...   758   759   760  \
0           17        1234          11305       3020  ...  0.10  0.00 -0.16   
1          125         182           6755      17204  ...  0.12  0.02 -0.14   
2          440         759          23924       2791  ...  0.12 -0.04 -0.17   
3           19          31            845        124  ...  0.09  0.02 -0.15   
4            9         147           3209        447  ...  0.17  0.04 -0.20   
..         ...         ...            ...        ...  ...   ...   ...   ...   
315          5           0             50         11  ...  0.14 -0.01 -0.14   
316          0           0              6          1  ...  0.19  0.01 -0.16   
317        768        1156          43138      14834  ...  0.13  0.01 -0.11   
318         17         119           2287        330  ...  0.13  0.00 -0.14   
319         80          66           4303        257  ...  0.12  0.03 -0.14   

      761   762   763   764   765   766   767  
0    0.05 -0.05 -0.19  0.24 -0.31 -0.01  0.05  
1    0.03 -0.10 -0.19  0.30 -0.28 -0.03  0.00  
2   -0.02 -0.14 -0.17  0.44 -0.40  0.01  0.05  
3    0.04 -0.12 -0.12  0.34 -0.31 -0.01  0.03  
4    0.04 -0.04 -0.21  0.33 -0.24 -0.01 -0.01  
..    ...   ...   ...   ...   ...   ...   ...  
315  0.03 -0.10 -0.23  0.36 -0.30 -0.02  0.00  
316  0.06 -0.11 -0.16  0.35 -0.23  0.02  0.00  
317  0.03 -0.09 -0.16  0.38 -0.28 -0.02  0.02  
318  0.07 -0.02 -0.19  0.39 -0.29 -0.03 -0.01  
319  0.06 -0.09 -0.21  0.38 -0.30 -0.02  0.03  

[320 rows x 988 columns]

In [ ]:
y

label
0       Openness
1       Openness
2       Openness
3       Openness
4       Openness
..           ...
315  Neuroticism
316  Neuroticism
317  Neuroticism
318  Neuroticism
319  Neuroticism

[320 rows x 1 columns]

##Label encoder terhadap kolom 'label' 

Keterangan label:

Agreeableness = 0

Conscientiousness = 1

Extraversion = 2

Neuroticism = 3

Openness = 4





In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X.iloc[:, 0] = le.fit_transform(X.iloc[:, 0])
y.iloc[:, 0] = le.fit_transform(y.iloc[:, 0])

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1951: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[selected_item_labels] = value


In [ ]:
y[y['label']==0].shape

(58, 1)

In [ ]:
X

jml_follower  jml_following  mention  hashtag  website  retweet  \
0             123            247     2899      178       59      311   
1             103            140      409      162       92      308   
2              44            217     2549      146      489      814   
3              14             37       99       13       23       63   
4              30             85      197      248      211       31   
..            ...            ...      ...      ...      ...      ...   
315             6             27        8        0        0        1   
316             0              2        0        0        0        0   
317            99            284     4762      708      936      386   
318            24             76      196        9       27       33   
319             7             59      156      146        9      104   

     media_url  tanda_baca  huruf_kapital  jml_tweet  ...   758   759   760  \
0           17        1234          11305       3020  ...  0.10  0.00 -0.16   
1          125         182           6755      17204  ...  0.12  0.02 -0.14   
2          440         759          23924       2791  ...  0.12 -0.04 -0.17   
3           19          31            845        124  ...  0.09  0.02 -0.15   
4            9         147           3209        447  ...  0.17  0.04 -0.20   
..         ...         ...            ...        ...  ...   ...   ...   ...   
315          5           0             50         11  ...  0.14 -0.01 -0.14   
316          0           0              6          1  ...  0.19  0.01 -0.16   
317        768        1156          43138      14834  ...  0.13  0.01 -0.11   
318         17         119           2287        330  ...  0.13  0.00 -0.14   
319         80          66           4303        257  ...  0.12  0.03 -0.14   

      761   762   763   764   765   766   767  
0    0.05 -0.05 -0.19  0.24 -0.31 -0.01  0.05  
1    0.03 -0.10 -0.19  0.30 -0.28 -0.03  0.00  
2   -0.02 -0.14 -0.17  0.44 -0.40  0.01  0.05  
3    0.04 -0.12 -0.12  0.34 -0.31 -0.01  0.03  
4    0.04 -0.04 -0.21  0.33 -0.24 -0.01 -0.01  
..    ...   ...   ...   ...   ...   ...   ...  
315  0.03 -0.10 -0.23  0.36 -0.30 -0.02  0.00  
316  0.06 -0.11 -0.16  0.35 -0.23  0.02  0.00  
317  0.03 -0.09 -0.16  0.38 -0.28 -0.02  0.02  
318  0.07 -0.02 -0.19  0.39 -0.29 -0.03 -0.01  
319  0.06 -0.09 -0.21  0.38 -0.30 -0.02  0.03  

[320 rows x 988 columns]

##Proses Scalling menggunakan MinMaxScaler

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
num_cols = []
for col in X.columns:
  num_cols.append(col)

In [ ]:
scaler = MinMaxScaler()

In [ ]:
df_copy = X
df_copy[num_cols] = scaler.fit_transform(df_copy[num_cols])
df_copy.head()

jml_follower  jml_following   mention   hashtag   website   retweet  \
0      0.495968       0.081357  0.296877  0.008433  0.013756  0.110127   
1      0.415323       0.046113  0.041884  0.007675  0.021450  0.109065   
2      0.177419       0.071476  0.261034  0.006917  0.114013  0.288244   
3      0.056452       0.012187  0.010138  0.000616  0.005363  0.022309   
4      0.120968       0.027997  0.020174  0.011750  0.049196  0.010977   

   media_url  tanda_baca  huruf_kapital  jml_tweet  ...   758       759  \
0   0.010712    0.239612       0.098202   0.043559  ...  0.52  0.290323   
1   0.078765    0.035340       0.058678   0.248211  ...  0.60  0.354839   
2   0.277253    0.147379       0.207818   0.040255  ...  0.60  0.161290   
3   0.011972    0.006019       0.007340   0.001775  ...  0.48  0.354839   
4   0.005671    0.028544       0.027875   0.006435  ...  0.80  0.419355   

        760      761       762       763       764       765       766  \
0  0.581395  0.78125  0.431373  0.102564  0.400000  0.495413  0.578947   
1  0.627907  0.71875  0.333333  0.102564  0.492308  0.522936  0.473684   
2  0.558140  0.56250  0.254902  0.153846  0.707692  0.412844  0.684211   
3  0.604651  0.75000  0.294118  0.282051  0.553846  0.495413  0.578947   
4  0.488372  0.75000  0.450980  0.051282  0.538462  0.559633  0.578947   

        767  
0  0.600000  
1  0.433333  
2  0.600000  
3  0.533333  
4  0.400000  

[5 rows x 988 columns]

In [ ]:
y.head(20)

label
0       4
1       4
2       4
3       4
4       4
5       4
6       4
7       4
8       4
9       4
10      4
11      4
12      4
13      4
14      4
15      4
16      4
17      4
18      4
19      4

##SMOTE

In [ ]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=42)
X_res, y_res = sm.fit_resample(df_copy, y)

##Split Dataset

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_res, y_res, test_size = 0.2, random_state = 42)

##Model ANN

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

import tensorflow as tf


y_train_cat = tf.keras.utils.to_categorical(y_res, num_classes=5)
y_test_cat = tf.keras.utils.to_categorical(y_test, num_classes=5)


classifier = Sequential()
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 100, kernel_initializer = 'uniform', activation = 'relu', input_dim = 988))
classifier.add(Dropout(rate=0.2))

# # Adding the second hidden layer
# classifier.add(Dense(units = 100, kernel_initializer = 'uniform', activation = 'relu'))

# # Adding the third hidden layer
# classifier.add(Dense(units = 140, kernel_initializer = 'uniform', activation = 'relu'))

# # Adding the fourth hidden layer
# classifier.add(Dense(units = 120, kernel_initializer = 'uniform', activation = 'relu'))

# # Adding the fifth hidden layer
# classifier.add(Dense(units = 100, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 5, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN | means applying SGD on the whole ANN
classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_res, y_train_cat, batch_size = 128, epochs = 100, verbose = 1)

score, acc = classifier.evaluate(X_res, y_train_cat,
                            batch_size=128)
print('Train score:', score)
print('Train accuracy:', acc)
# Part 3 - Making predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)

score, acc = classifier.evaluate(X_test, y_test_cat,
                            batch_size=128)
print('Test score:', score)
print('Test accuracy:', acc)

Epoch 1/100
4/4 [==============================] - 1s 11ms/step - loss: 1.6239 - accuracy: 0.1677
Epoch 2/100
4/4 [==============================] - 0s 7ms/step - loss: 1.6073 - accuracy: 0.2043
Epoch 3/100
4/4 [==============================] - 0s 8ms/step - loss: 1.5983 - accuracy: 0.2430
Epoch 4/100
4/4 [==============================] - 0s 9ms/step - loss: 1.5884 - accuracy: 0.2710
Epoch 5/100
4/4 [==============================] - 0s 10ms/step - loss: 1.5843 - accuracy: 0.2968
Epoch 6/100
4/4 [==============================] - 0s 7ms/step - loss: 1.5815 - accuracy: 0.2817
Epoch 7/100
4/4 [==============================] - 0s 9ms/step - loss: 1.5705 - accuracy: 0.3054
Epoch 8/100
4/4 [==============================] - 0s 12ms/step - loss: 1.5733 - accuracy: 0.2860
Epoch 9/100
4/4 [==============================] - 0s 6ms/step - loss: 1.5612 - accuracy: 0.3484
Epoch 10/100
4/4 [==============================] - 0s 7ms/step - loss: 1.5554 - accuracy: 0.3290
Epoch 11/100
4/4 [========

##Confussion Matrix

In [ ]:
y_pred_cat = y_pred.argmax(axis=1)

In [ ]:
y_pred_cat

array([3, 0, 1, 4, 1, 4, 0, 4, 0, 0, 3, 0, 3, 1, 1, 3, 2, 1, 4, 1, 1, 4,
       3, 2, 3, 3, 0, 1, 4, 4, 0, 0, 2, 3, 4, 0, 1, 2, 2, 3, 3, 4, 2, 1,
       0, 0, 0, 0, 4, 4, 2, 0, 0, 1, 0, 4, 4, 2, 1, 3, 0, 0, 3, 4, 3, 3,
       4, 4, 1, 2, 4, 4, 1, 2, 1, 2, 0, 1, 4, 1, 2, 3, 0, 4, 1, 3, 3, 4,
       3, 3, 0, 4, 2])

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
print(confusion_matrix(y_test, y_pred_cat))
print(accuracy_score(y_test, y_pred_cat))
print(classification_report(y_test, y_pred_cat))

[[20  0  0  0  1]
 [ 1 15  1  0  1]
 [ 0  2 11  0  1]
 [ 0  1  1 18  2]
 [ 0  0  0  1 17]]
0.8709677419354839
              precision    recall  f1-score   support

           0       0.95      0.95      0.95        21
           1       0.83      0.83      0.83        18
           2       0.85      0.79      0.81        14
           3       0.95      0.82      0.88        22
           4       0.77      0.94      0.85        18

    accuracy                           0.87        93
   macro avg       0.87      0.87      0.87        93
weighted avg       0.88      0.87      0.87        93



In [ ]:
# from joblib import Parallel, delayed
# import joblib
 
 
# # Save the model as a pickle in a file
# joblib.dump(classifier, 'scenario_4_TA.pkl')

# # Load the model from the file
# classifier_from_joblib = joblib.load('scenario_4_TA.pkl')
 
# # Use the loaded model to make predictions
# classifier_from_joblib.predict(X_test)

In [ ]:
# y_pred = classifier_from_joblib.predict(X_test)

# from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
# print(confusion_matrix(y_test, y_pred_cat))
# print(accuracy_score(y_test, y_pred_cat))
# print(classification_report(y_test, y_pred_cat))